services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_MODEL=${MODEL_NAME}
      - HISTORY_MAX_LEN=${HISTORY_MAX_LEN}
      - STUPID_CHECK=${STUPID_CHECK}

volumes:
  ollama:
