// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TgBot.Admin.Api.Database;

#nullable disable

namespace TgBot.Admin.Api.Database.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20251227143746_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TgBot.Admin.Api.Settings.Chats.ChatSettings", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<bool>("JokeSubscribed")
                        .HasColumnType("boolean")
                        .HasColumnName("joke_subscribed");

                    b.Property<string>("JokeTopic")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("joke_topic");

                    b.Property<bool>("StupidityCheck")
                        .HasColumnType("boolean")
                        .HasColumnName("stupidity_check");

                    b.HasKey("ChatId");

                    b.ToTable("chat_settings", (string)null);
                });

            modelBuilder.Entity("TgBot.Admin.Api.Settings.Global.GlobalSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("AiInstructions")
                        .HasColumnType("text")
                        .HasColumnName("ai_instructions");

                    b.Property<string>("DailyJokesTime")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("daily_jokes_time");

                    b.Property<int?>("HistoryMaxLen")
                        .HasColumnType("integer")
                        .HasColumnName("history_max_len");

                    b.Property<string>("JokeInstructions")
                        .HasColumnType("text")
                        .HasColumnName("joke_instructions");

                    b.Property<string>("LlmModel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("llm_model");

                    b.Property<double?>("StupidCheck")
                        .HasColumnType("double precision")
                        .HasColumnName("stupid_check");

                    b.Property<string>("StupidityInstructions")
                        .HasColumnType("text")
                        .HasColumnName("stupidity_instructions");

                    b.HasKey("Id");

                    b.ToTable("settings_global", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
